// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznlSlXpClb5MAfhYjd_3kXfDBpuh58GM',
    appId: '1:374501713742:web:9b072f87f484a33feee01f',
    messagingSenderId: '374501713742',
    projectId: 'carnest-2f652',
    authDomain: 'carnest-2f652.firebaseapp.com',
    storageBucket: 'carnest-2f652.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOj7c_zeCwAzvhS16zBWQ4_iIfIIN4snI',
    appId: '1:374501713742:android:e706a00346990de0eee01f',
    messagingSenderId: '374501713742',
    projectId: 'carnest-2f652',
    storageBucket: 'carnest-2f652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMO3rsN8YeZB9VvFwFiw0fqCc1EwQ5Sc',
    appId: '1:374501713742:ios:a664235dba91f749eee01f',
    messagingSenderId: '374501713742',
    projectId: 'carnest-2f652',
    storageBucket: 'carnest-2f652.appspot.com',
    androidClientId: '374501713742-a4vojg23hito01kbr8ac5nvq0efvd2i9.apps.googleusercontent.com',
    iosClientId: '374501713742-eitkis5a8rqefvrcgfahcs00ggkk463e.apps.googleusercontent.com',
    iosBundleId: 'com.example.productShareSuzuki',
  );

}